name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"

      - name: Configure git
        run: |
          git config user.email "akaan.qualrus@gmail.com"
          git config user.name "Akaan Qualrus"
      - run: yarn --frozen-lockfile
      - run: yarn publish --new-version ${{ github.event.release.tag_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
